name: Lyzer ETL Checks

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  Code-Style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        run: |
          pip install -r dev-requirements.txt
      - name: Lint and Docs Styling
        run: |
          python -m flake8 main.py src/ --max-line-length 100
          python -m pydocstyle main.py src/

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        run: |
          pip install -r dev-requirements.txt
      - name: Build executable
        run: |
          python -m pyinstaller --onefile --name=Lyzer-ETL --clean --distpath=dist/ --add-data "version.txt:." main.py
