on:
  push:
    branches:
      - trunk

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: Lyzer-ETL
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install
      - name: "Build Exe"
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pipenv run pyinstaller --onefile --name=Lyzer-ETL --clean --distpath=dist/ --add-data "version.txt:." main.py
      - name: "Upload Exe"
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} dist/Lyzer-ETL
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
